apiVersion: v1
kind: PersistentVolume
metadata:
    name: mariadb-pv
    namespace: popote
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: /mnt/data/mariadb