# Use the lightweight Nginx image from the previous stage for the nginx container
#FROM nginx:stable-alpine
#FROM nginx:stable-perl
#FROM nginx:alpine-perl
FROM nginx


RUN echo "==========================="; \
    echo "|                         |"; \
    echo "|       NGINX             |"; \
    echo "|                         |"; \
    echo "==========================="


#install optionnels
RUN apt-get update
RUN apt-get install -y net-tools
RUN apt-get install -y iputils-ping
RUN apt-get install certbot python3-certbot-nginx -y

# Copy the nginx configuration file
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Set the timezone (change this to your local timezone)
RUN echo "Europe/Paris" | tee /etc/timezone
RUN dpkg-reconfigure --frontend noninteractive tzdata

#copy files for https
#COPY ./nginx/cert /etc/letsencrypt/


VOLUME /etc/letsencrypt/ /etc/letsencrypt/ :ro

# Expose the port 80
EXPOSE 80
EXPOSE 443

# Start Nginx to serve the application
#CMD ["nginx", "-g", "daemon off;"]