# Use the lightweight Nginx image from the previous stage for the nginx container
FROM nginx:stable-alpine
# Copy the nginx configuration file
COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
# Expose the port 80
EXPOSE 8080
# Start Nginx to serve the application
CMD ["nginx", "-g", "daemon off;"]