# Use the lightweight Nginx image from the previous stage for the nginx container
#FROM nginx:stable-alpine
FROM nginx:stable-perl
# Copy the nginx configuration file

RUN apt-get update

COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
# Expose the port 80
EXPOSE 80
# Start Nginx to serve the application
CMD ["nginx", "-g", "daemon off;"]