
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: popote
  name: deployment_popote_monoPod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: popote_monoPod
  template:
    metadata:
      labels:
        app: deployment_popote_monoPod
    spec:
      containers:
      - name: popote_mariadb
        image: popote_vuejs_k8s-mariadb
        ports:
          - containerPort: 3306
          
      - name: popote_backend
        image: popote_vuejs_k8s-backend
        ports:
          - containerPort: 3000
      
      - name: popote_frontend
        image: popote_vuejs_k8s-frontend
        ports:
          - containerPort: 8080
      
      - name: popote_nginx
        image: popote_vuejs_k8s-nginx
        ports:
          - containerPort: 80
          - containerPort: 3000
      