apiVersion: v1
kind: PersistentVolume
metadata:
  name: letsencript
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/etc/letsencrypt"