apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume_letsencript
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/etc/letsencrypt"