apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume_letsencript-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi