apiVersion: v1
kind: Service
metadata:
  name: popote-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:

  - name: backend-port
    protocol: TCP
    port: 3000
    targetPort: backend-svc

  - name: frontend-port
    protocol: TCP
    port: 8080
    targetPort: frontend-svc

  - name: mariadb-port
    protocol: TCP
    port: 3306
    targetPort: mariadb-svc
    